# Basic
hard_tabs = true
max_width = 100
use_small_heuristics = "Max"

# Imports
reorder_imports = true

# Consistency
newline_style = "Unix"

# Misc
chain_width = 80
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true

# Disabled as it is an unstable feature only available in nightly builds
# trailing_comma = "Vertical"
# trailing_semicolon = false
# match_arm_blocks = false
# binop_separator = "Back"
# spaces_around_ranges = false
# reorder_impl_items = false
# imports_granularity = "Crate"
