[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[workspace]
members = [
	"node",
	"runtime/mainnet",
	"runtime/devnet",
	"pallets/motion"
]
