# Polkadot should be build with 'fast-runtime' feature
# cargo build --release --features fast-runtime from a branch with sudo pallet
[relaychain]
chain = "polkadot-local"
default_command = "./bin/polkadot"

	[[relaychain.nodes]]
	name = "alice"
	validator = true

	[[relaychain.nodes]]
	name = "bob"
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
	validator = true

	[[relaychain.nodes]]
	name = "dave"
	validator = true

[[parachains]]
id = 2058
addToGenesis = true
cumulus_based = true
chain = "mainnet-local"

	[[parachains.collators]]
	name = "watr-collator01"
	command = "./target/release/watr-node"
	ws_port = 9933

	[[parachains.collators]]
	name = "watr-collator02"
	ws_port = 9822
	command = "./target/release/watr-node"
