name: Build Binary

on:
  workflow_dispatch:
    inputs:
      ref:
        description: ref to build binary from
        required: true

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cpu: ["", "skylake"]
    env:
      RUSTFLAGS: "-C target-cpu=${{ matrix.cpu }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Install protoc
        run: |
           sudo apt-get install -y protobuf-compiler
           protoc --version
      - name: Setup Rust toolchain
        run: rustup show
      - name: Build Node
        run: cargo build --profile=production --all
      - name: Save parachain binary
        if: ${{ matrix.cpu == '' }}
        run: |
          mkdir -p build
          cp target/production/watr-node build/watr-node
      - name: Save parachain custom binary
        if: ${{ matrix.cpu != '' }}
        run: |
          mkdir -p build
          cp target/production/watr-node build/watr-node-${{matrix.cpu}}
      - name: Upload binary
        uses: actions/upload-artifact@v3.1.2
        with:
          name: binaries
          path: build
