# Test storage migration using try-runtume on PRs with label "migration-devnet"
name: Test storage migration

on:
  pull_request:
    types: [labeled, synchronize]
  push:
    branches: [ main ]

jobs:
  try_runtime:
    if: contains(github.event.pull_request.labels.*.name, 'migration-devnet')
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          components: rustfmt, clippy

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install try-runtime
        run: cargo install --git https://github.com/paritytech/try-runtime-cli --locked

      - run: |
          cargo build -p watr-node --locked --release --no-default-features --features try-runtime && \
          try-runtime --runtime ./target/release/wbuild/watr-devnet-runtime/target/wasm32-unknown-unknown/release/watr_devnet_runtime.wasm \
              on-runtime-upgrade live --uri wss://rpc.dev.watr.org:443
        env:
          RUST_LOG: remote-ext=debug,runtime=debug
